import type { ShopPageModel } from "./ecommerce";

const shopProducts: ShopPageModel["products"] = [
  {
    id: "s1",
    name: "Hummingbird Printed Toner",
    brand: "Mugnee Ritual",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "White",
    size: "S",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s2",
    name: "Hummingbird Printed Cream",
    brand: "Aurelia Lab",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Green",
    size: "M",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s3",
    name: "Hummingbird Printed Mask",
    brand: "Flora Care",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "White",
    size: "L",
    price: 21.99,
    compareAt: 27.9,
    rating: 4,
    badge: "-8%",
    image:
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s4",
    name: "Hummingbird Printed Balm",
    brand: "Mugnee Pure",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Gold",
    size: "M",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s5",
    name: "Hummingbird Printed Mist",
    brand: "Aqua Botanics",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Green",
    size: "XL",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s6",
    name: "Hummingbird Printed Lotion",
    brand: "Mugnee Daily",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Gold",
    size: "S",
    price: 21.99,
    compareAt: 27.9,
    rating: 4,
    badge: "-8%",
    image:
      "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s7",
    name: "Hummingbird Printed Fragrance",
    brand: "Grace & Leaf",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Gold",
    size: "XL",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1547887538-e3a2f32cb1cc?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s8",
    name: "Hummingbird Printed Cleanser",
    brand: "Herbal Muse",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "White",
    size: "M",
    price: 21.99,
    compareAt: 27.9,
    rating: 5,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s9",
    name: "Hummingbird Printed Refill",
    brand: "Cove & Salt",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Green",
    size: "XL",
    price: 21.99,
    compareAt: 27.9,
    rating: 4,
    badge: "-8%",
    image:
      "https://images.unsplash.com/photo-1601049541289-9b1b7bbbfe19?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s10",
    name: "Mountain Soft Body Cream",
    brand: "Graphic Corner",
    category: "Arts & Crafts",
    designer: "Graphic Corner",
    color: "Gold",
    size: "L",
    price: 9,
    compareAt: 14,
    rating: 4,
    image:
      "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s11",
    name: "Mountain Green Wash",
    brand: "Graphic Corner",
    category: "Arts & Crafts",
    designer: "Graphic Corner",
    color: "Green",
    size: "M",
    price: 18.5,
    compareAt: 24,
    rating: 5,
    badge: "New",
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s12",
    name: "Mountain White Polish",
    brand: "Mugnee Studio",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "White",
    size: "XL",
    price: 34.99,
    compareAt: 42,
    rating: 5,
    badge: "-8%",
    image:
      "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=520&q=80",
  },
  {
    id: "s13",
    name: "Gold Ritual Serum",
    brand: "Mugnee Ritual",
    category: "Arts & Crafts",
    designer: "Studio Design",
    color: "Gold",
    size: "S",
    price: 59,
    compareAt: 70,
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?auto=format&fit=crop&w=520&q=80",
  },
];

export const shopPageModel: ShopPageModel = {
  navigation: [
    { label: "Home", href: "/" },
    { label: "Shop", href: "/shop" },
    { label: "Blog", href: "/blog" },
    { label: "About Us", href: "/about" },
    { label: "Contact", href: "/contact" },
    { label: "Features", href: "/shop" },
  ],
  products: shopProducts,
  newProducts: shopProducts.slice(0, 3),
  colorFilters: [
    { label: "Gold", count: 6 },
    { label: "Green", count: 4 },
    { label: "White", count: 8 },
  ],
  sizeFilters: [
    { label: "S", count: 3 },
    { label: "M", count: 5 },
    { label: "L", count: 2 },
    { label: "XL", count: 7 },
  ],
  brandMarks: ["PRESTIGES", "BUSINESS", "PRESTIGE", "SHOPNAME", "PHOTOGRAPH", "RETROGE"],
  instagramImages: [
    "https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=180&q=70",
    "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=180&q=70",
    "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=180&q=70",
    "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?auto=format&fit=crop&w=180&q=70",
    "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?auto=format&fit=crop&w=180&q=70",
    "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=180&q=70",
  ],
};
